name: Deploy React App to S3

on:
  pull_request:
    branches:
      - main # Cambia a la rama que quieras monitorear

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Configurar Node.js (para instalar dependencias)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    # Paso 3: Instalar dependencias
    - name: Install dependencies
      run: npm install

    # Paso 4: Construir la aplicación
    - name: Build React app
      run: npm run build

    # Paso 5: Ejecutar Linter (npm run lint)
    - name: Run Linter
      run: npm run lint
